In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [3]:
df=pd.read_csv('datasets/advertising.csv')
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country            Timestamp  Clicked on Ad  
0                   Tunisia  2016-03-27 00:53:11              0  
1                     Nauru  2016-04-04 01:39:02              0  
2                San Marino  2016-03-13 20:35:42              0  
3                     Italy  2016-01-10 02:31:19              0  
4                   Iceland  2016-06-03 03:36:18              0  
..                      ...                  ...            ...  
995                 Lebanon  2016-02-11 21:49:00              1  
996  Bosnia and Herzegovina  2016-04-22 02:07:01              1  
997                Mongolia  2016-02-01 17:24:57              1  
998               Guatemala  2016-03-24 02:35:54              0  
999                  Brazil  2016-06-03 21:43:21              1  

[1000 rows x 10 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [5]:
df['Timestamp']=pd.to_datetime(df['Timestamp'],format='%Y-%m-%d %H:%M:%S',errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Daily Time Spent on Site  1000 non-null   float64       
 1   Age                       1000 non-null   int64         
 2   Area Income               1000 non-null   float64       
 3   Daily Internet Usage      1000 non-null   float64       
 4   Ad Topic Line             1000 non-null   object        
 5   City                      1000 non-null   object        
 6   Male                      1000 non-null   int64         
 7   Country                   1000 non-null   object        
 8   Timestamp                 1000 non-null   datetime64[ns]
 9   Clicked on Ad             1000 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 78.2+ KB


In [8]:
def ext_season(x):
    if x.month in [12,1,2]:
        return 'Winter'
    elif x.month in [3,4,5]:
        return 'Spring'
    elif x.month in [6,7,8]:
        return 'Summer'
    else:
        return 'Autumn'

def ext_period(x):
    if x.hour in range(0,13):
        return 'Morning'
    elif x.hour in range(13,19):
        return 'AfterNoon'
    else:
        return 'Evening'

In [9]:
df['Season']=df['Timestamp'].apply(ext_season)
df['Period']=df['Timestamp'].apply(ext_period)
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country           Timestamp  Clicked on Ad  Season  \
0                   Tunisia 2016-03-27 00:53:11              0  Spring   
1                     Nauru 2016-04-04 01:39:02              0  Spring   
2                San Marino 2016-03-13 20:35:42              0  Spring   
3                     Italy 2016-01-10 02:31:19              0  Winter   
4                   Iceland 2016-06-03 03:36:18              0  Summer   
..                      ...                 ...            ...     ...   
995                 Lebanon 2016-02-11 21:49:00              1  Winter   
996  Bosnia and Herzegovina 2016-04-22 02:07:01              1  Spring   
997                Mongolia 2016-02-01 17:24:57              1  Winter   
998               Guatemala 2016-03-24 02:35:54              0  Spring   
999                  Brazil 2016-06-03 21:43:21              1  Summer   

        Period  
0      Morning  
1      Morning  
2      Evening  
3      Morning  
4      Morning  
..         ...  
995    Evening  
996    Morning  
997  AfterNoon  
998    Morning  
999    Evening  

[1000 rows x 12 columns]

In [10]:
df=pd.get_dummies(df,columns=['City','Country','Season','Period'],drop_first=True)
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line  Male           Timestamp  \
0       Cloned 5thgeneration orchestration     0 2016-03-27 00:53:11   
1       Monitored national standardization     1 2016-04-04 01:39:02   
2         Organic bottom-line service-desk     0 2016-03-13 20:35:42   
3    Triple-buffered reciprocal time-frame     1 2016-01-10 02:31:19   
4            Robust logistical utilization     0 2016-06-03 03:36:18   
..                                     ...   ...                 ...   
995          Fundamental modular algorithm     1 2016-02-11 21:49:00   
996        Grass-roots cohesive monitoring     1 2016-04-22 02:07:01   
997           Expanded intangible solution     1 2016-02-01 17:24:57   
998   Proactive bandwidth-monitored policy     0 2016-03-24 02:35:54   
999        Virtual 5thgeneration emulation     0 2016-06-03 21:43:21   

     Clicked on Ad  City_Adamside  City_Adamsstad  ...  Country_Vietnam  \
0                0              0               0  ...                0   
1                0              0               0  ...                0   
2                0              0               0  ...                0   
3                0              0               0  ...                0   
4                0              0               0  ...                0   
..             ...            ...             ...  ...              ...   
995              1              0               0  ...                0   
996              1              0               0  ...                0   
997              1              0               0  ...                0   
998              0              0               0  ...                0   
999              1              0               0  ...                0   

     Country_Wallis and Futuna  Country_Western Sahara  Country_Yemen  \
0                            0                       0              0   
1                            0                       0              0   
2                            0                       0              0   
3                            0                       0              0   
4                            0                       0              0   
..                         ...                     ...            ...   
995                          0                       0              0   
996                          0                       0              0   
997                          0                       0              0   
998                          0                       0              0   
999                          0                       0              0   

     Country_Zambia  Country_Zimbabwe  Season_Summer  Season_Winter  \
0                 0                 0              0              0   
1                 0                 0              0              0   
2                 0                 0              0              0   
3                 0                 0              0              1   
4                 0                 0              1              0   
..              ...               ...            ...       

In [27]:
x=df.drop(['Clicked on Ad','Timestamp','Ad Topic Line'],axis=1)
y=df['Clicked on Ad']
x

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
0                       68.95   35     61833.90                256.09     0   
1                       80.23   31     68441.85                193.77     1   
2                       69.47   26     59785.94                236.50     0   
3                       74.15   29     54806.18                245.89     1   
4                       68.37   35     73889.99                225.58     0   
..                        ...  ...          ...                   ...   ...   
995                     72.97   30     71384.57                208.58     1   
996                     51.30   45     67782.17                134.42     1   
997                     51.63   51     42415.72                120.37     1   
998                     55.55   19     41920.79                187.95     0   
999                     45.01   26     29875.80                178.35     0   

     City_Adamside  City_Adamsstad  City_Alanview  City_Alexanderfurt  \
0                0               0              0                   0   
1                0               0              0                   0   
2                0               0              0                   0   
3                0               0              0                   0   
4                0               0              0                   0   
..             ...             ...            ...                 ...   
995              0               0              0                   0   
996              0               0              0                   0   
997              0               0              0                   0   
998              0               0              0                   0   
999              0               0              0                   0   

     City_Alexanderview  ...  Country_Vietnam  Country_Wallis and Futuna  \
0                     0  ...                0                          0   
1                     0  ...                0                          0   
2                     0  ...                0                          0   
3                     0  ...                0                          0   
4                     0  ...                0                          0   
..                  ...  ...              ...                        ...   
995                   0  ...                0                          0   
996                   0  ...                0                          0   
997                   0  ...                0                          0   
998                   0  ...                0                          0   
999                   0  ...                0                          0   

     Country_Western Sahara  Country_Yemen  Country_Zambia  Country_Zimbabwe  \
0                         0              0               0                 0   
1                         0              0               0                 0   
2                         0              0               0                 0   
3                         0              0               0                 0   
4                         0              0               0                 0   
..                      ...            ...             ...               ...   
995                       0              0               0                 0   
996                       0              0               0                 0   
997                       0              0               0                 0   
998                       0              0               0                 0   
999                       0              0               0                 0   

     Season_Summer  Season_Winter  Period_Evening  Period_Morning  
0                0              0               0               1  
1                0              0               0               1  
2                0              0               1               0  
3                0              1

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)


In [29]:
y_train.value_counts()

1    376
0    374
Name: Clicked on Ad, dtype: int64

In [30]:
x_train

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
881                     79.18   31     58443.99                236.96     0   
510                     57.86   30     18819.34                166.86     0   
461                     32.99   45     49282.87                177.46     0   
97                      39.94   41     64927.19                156.30     0   
175                     71.74   35     72423.97                227.56     0   
..                        ...  ...          ...                   ...   ...   
778                     52.67   44     14775.50                191.26     0   
229                     76.06   23     58633.63                201.04     0   
180                     39.85   38     31343.39                145.96     0   
240                     80.03   44     24030.06                150.84     0   
685                     76.27   27     60082.66                226.69     1   

     City_Adamside  City_Adamsstad  City_Alanview  City_Alexanderfurt  \
881              0               0              0                   0   
510              0               0              0                   0   
461              0               0              0                   0   
97               0               0              0                   0   
175              0               0              0                   0   
..             ...             ...            ...                 ...   
778              0               0              0                   0   
229              0               0              0                   0   
180              0               0              0                   0   
240              0               0              0                   0   
685              0               0              0                   0   

     City_Alexanderview  ...  Country_Vietnam  Country_Wallis and Futuna  \
881                   0  ...                0                          0   
510                   0  ...                0                          0   
461                   0  ...                0                          0   
97                    0  ...                0                          0   
175                   0  ...                0                          0   
..                  ...  ...              ...                        ...   
778                   0  ...                0                          0   
229                   0  ...                0                          0   
180                   0  ...                1                          0   
240                   0  ...                0                          0   
685                   0  ...                0                          0   

     Country_Western Sahara  Country_Yemen  Country_Zambia  Country_Zimbabwe  \
881                       0              0               0                 0   
510                       0              0               0                 0   
461                       0              0               0                 0   
97                        0              0               0                 0   
175                       0              0               0                 0   
..                      ...            ...             ...               ...   
778                       0              0               0                 0   
229                       0              0               0                 0   
180                       0              0               0                 0   
240                       0              0               0                 0   
685                       0              0               0                 0   

     Season_Summer  Season_Winter  Period_Evening  Period_Morning  
881              0              1               1               0  
510              1              0               0               0  
461              0              0               1               0  
97               0              1

In [31]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
#x_train[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage']]=scaler.fit_transform(x_train[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage']])
#x_test[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage']]=scaler.transform(x_test[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage']])
#or
#x[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage']]=scaler.fit_transform(x[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage']])
#splitting
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.86492291, -0.54930418,  0.26144045, ...,  1.51310069,
         1.84709629, -1.09812675],
       [-0.48654423, -0.66223679, -2.67666017, ..., -0.66089455,
        -0.54139029, -1.09812675],
       [-2.06304458,  1.03175226, -0.41784107, ..., -0.66089455,
         1.84709629, -1.09812675],
       ...,
       [-1.62819165,  0.24122404, -1.74802309, ...,  1.51310069,
        -0.54139029,  0.91064169],
       [ 0.9188041 ,  0.91881966, -2.29029411, ..., -0.66089455,
        -0.54139029, -1.09812675],
       [ 0.68045905, -1.0010346 ,  0.38294505, ..., -0.66089455,
        -0.54139029,  0.91064169]])

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,fbeta_score,classification_report

In [39]:
models={
    'LR':LogisticRegression(),
    'KNN':KNeighborsClassifier(),
    'DT':DecisionTreeClassifier(),
    'SVC':SVC(),
    'NB':GaussianNB(),
    'XGC':XGBClassifier(),
    'RF':RandomForestClassifier()
    
}

In [40]:
for name,model in  models.items():
    print(f'using {name}: ')
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f'Training Accuracy :{accuracy_score(y_train,model.predict(x_train))}')
    print(f'Testing Accuracy :{accuracy_score(y_test,y_pred)}')
    print(f'Confusion matrix:\n {confusion_matrix(y_test,y_pred)}')
    print(f'Recall: {recall_score(y_test,y_pred)}')
    print(f'precision: {precision_score(y_test,y_pred)}')
    print(f'F1-score: {f1_score(y_test,y_pred)}')
    print(f'Fbeta-score: {fbeta_score(y_test,y_pred,beta=0.5)}')
    print(classification_report(y_test,y_pred))
    print('-'*33)
    

using LR: 
Training Accuracy :1.0
Testing Accuracy :0.952
Confusion matrix:
 [[121   5]
 [  7 117]]
Recall: 0.9435483870967742
precision: 0.9590163934426229
F1-score: 0.951219512195122
Fbeta-score: 0.9558823529411765
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       126
           1       0.96      0.94      0.95       124

    accuracy                           0.95       250
   macro avg       0.95      0.95      0.95       250
weighted avg       0.95      0.95      0.95       250

---------------------------------
using KNN: 
Training Accuracy :0.8986666666666666
Testing Accuracy :0.748
Confusion matrix:
 [[ 79  47]
 [ 16 108]]
Recall: 0.8709677419354839
precision: 0.6967741935483871
F1-score: 0.7741935483870968
Fbeta-score: 0.7258064516129031
              precision    recall  f1-score   support

           0       0.83      0.63      0.71       126
           1       0.70      0.87      0.77       124

    accuracy            

C:\Users\mgama\conda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:03:13] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy :1.0
Testing Accuracy :0.972
Confusion matrix:
 [[123   3]
 [  4 120]]
Recall: 0.967741935483871
precision: 0.975609756097561
F1-score: 0.97165991902834
Fbeta-score: 0.974025974025974
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       126
           1       0.98      0.97      0.97       124

    accuracy                           0.97       250
   macro avg       0.97      0.97      0.97       250
weighted avg       0.97      0.97      0.97       250

---------------------------------
using RF: 
Training Accuracy :1.0
Testing Accuracy :0.972
Confusion matrix:
 [[122   4]
 [  3 121]]
Recall: 0.9758064516129032


In [43]:
model=RandomForestClassifier()
model.fit(x_train,y_train)


RandomForestClassifier()

In [46]:
x.columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Male', 'City_Adamside', 'City_Adamsstad',
       'City_Alanview', 'City_Alexanderfurt', 'City_Alexanderview',
       ...
       'Country_Vietnam', 'Country_Wallis and Futuna',
       'Country_Western Sahara', 'Country_Yemen', 'Country_Zambia',
       'Country_Zimbabwe', 'Season_Summer', 'Season_Winter', 'Period_Evening',
       'Period_Morning'],
      dtype='object', length=1213)

In [42]:
import joblib
joblib.dump(model,'model.h5')
joblib.dump(scaler,'scaler.h5')

['scaler.h5']

In [47]:
df=pd.read_csv('datasets/data.csv')
df

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [49]:
df=pd.get_dummies(df,columns=['purpose'],drop_first=True)
df

credit.policy  int.rate  installment  log.annual.inc    dti  fico  \
0                 1    0.1189       829.10       11.350407  19.48   737   
1                 1    0.1071       228.22       11.082143  14.29   707   
2                 1    0.1357       366.86       10.373491  11.63   682   
3                 1    0.1008       162.34       11.350407   8.10   712   
4                 1    0.1426       102.92       11.299732  14.97   667   
...             ...       ...          ...             ...    ...   ...   
9573              0    0.1461       344.76       12.180755  10.39   672   
9574              0    0.1253       257.70       11.141862   0.21   722   
9575              0    0.1071        97.81       10.596635  13.09   687   
9576              0    0.1600       351.58       10.819778  19.18   692   
9577              0    0.1392       853.43       11.264464  16.28   732   

      days.with.cr.line  revol.bal  revol.util  inq.last.6mths  delinq.2yrs  \
0           5639.958333      28854        52.1               0            0   
1           2760.000000      33623        76.7               0            0   
2           4710.000000       3511        25.6               1            0   
3           2699.958333      33667        73.2               1            0   
4           4066.000000       4740        39.5               0            1   
...                 ...        ...         ...             ...          ...   
9573       10474.000000     215372        82.1               2            0   
9574        4380.000000        184         1.1               5            0   
9575        3450.041667      10036        82.9               8            0   
9576        1800.000000          0         3.2               5            0   
9577        4740.000000      37879        57.0               6            0   

      pub.rec  not.fully.paid  purpose_credit_card  \
0           0               0                    0   
1           0               0                    1   
2           0               0                    0   
3           0               0                    0   
4           0               0                    1   
...       ...             ...                  ...   
9573        0               1                    0   
9574        0               1                    0   
9575        0               1                    0   
9576        0               1                    0   
9577        0               1                    0   

      purpose_debt_consolidation  purpose_educational  \
0                              1                    0   
1                              0                    0   
2                              1                    0   
3                              1                    0   
4                              0                    0   
...                          ...                  ...   
9573                           0                    0   
9574                           0                    0   
9575                           1                    0   
9576                           0                    0   
9577                           1                    0   

      purpose_home_improvement  purpose_major_purchase  purpose_small_business  
0                            0                       0                       0  
1                            0                       0                       0  
2                            0                       0                       0  
3                            0                       0                       0  
4                            0                       0                       0  
...                        ...                     ...                     ...  
9573                         0                       0                       0  
9574                         0                       0                       0  
9575                         0                       0                       0  
9576        

In [50]:
x=df.drop('not.fully.paid',axis=1)
y=df['not.fully.paid']
x

credit.policy  int.rate  installment  log.annual.inc    dti  fico  \
0                 1    0.1189       829.10       11.350407  19.48   737   
1                 1    0.1071       228.22       11.082143  14.29   707   
2                 1    0.1357       366.86       10.373491  11.63   682   
3                 1    0.1008       162.34       11.350407   8.10   712   
4                 1    0.1426       102.92       11.299732  14.97   667   
...             ...       ...          ...             ...    ...   ...   
9573              0    0.1461       344.76       12.180755  10.39   672   
9574              0    0.1253       257.70       11.141862   0.21   722   
9575              0    0.1071        97.81       10.596635  13.09   687   
9576              0    0.1600       351.58       10.819778  19.18   692   
9577              0    0.1392       853.43       11.264464  16.28   732   

      days.with.cr.line  revol.bal  revol.util  inq.last.6mths  delinq.2yrs  \
0           5639.958333      28854        52.1               0            0   
1           2760.000000      33623        76.7               0            0   
2           4710.000000       3511        25.6               1            0   
3           2699.958333      33667        73.2               1            0   
4           4066.000000       4740        39.5               0            1   
...                 ...        ...         ...             ...          ...   
9573       10474.000000     215372        82.1               2            0   
9574        4380.000000        184         1.1               5            0   
9575        3450.041667      10036        82.9               8            0   
9576        1800.000000          0         3.2               5            0   
9577        4740.000000      37879        57.0               6            0   

      pub.rec  purpose_credit_card  purpose_debt_consolidation  \
0           0                    0                           1   
1           0                    1                           0   
2           0                    0                           1   
3           0                    0                           1   
4           0                    1                           0   
...       ...                  ...                         ...   
9573        0                    0                           0   
9574        0                    0                           0   
9575        0                    0                           1   
9576        0                    0                           0   
9577        0                    0                           1   

      purpose_educational  purpose_home_improvement  purpose_major_purchase  \
0                       0                         0                       0   
1                       0                         0                       0   
2                       0                         0                       0   
3                       0                         0                       0   
4                       0                         0                       0   
...                   ...                       ...                     ...   
9573                    0                         0                       0   
9574                    0                         0                       0   
9575                    0                         0                       0   
9576                    0                         1                       0   
9577                    0                         0                       0   

      purpose_small_business  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  
...                      ...  
9573                       0  
9574                       0  
9575                       0  
9576                       0  
9577                       0  

[9578 rows x 18 columns]

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [52]:
y_train.value_counts()

0    6423
1    1239
Name: not.fully.paid, dtype: int64

In [54]:
from imblearn.over_sampling import SMOTE
sampler=SMOTE()
x_train,y_train=sampler.fit_resample(x_train,y_train)
y_train.value_counts()

0    6423
1    6423
Name: not.fully.paid, dtype: int64

In [55]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)


In [56]:
for name,model in  models.items():
    print(f'using {name}: ')
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f'Training Accuracy :{accuracy_score(y_train,model.predict(x_train))}')
    print(f'Testing Accuracy :{accuracy_score(y_test,y_pred)}')
    print(f'Confusion matrix:\n {confusion_matrix(y_test,y_pred)}')
    print(f'Recall: {recall_score(y_test,y_pred)}')
    print(f'precision: {precision_score(y_test,y_pred)}')
    print(f'F1-score: {f1_score(y_test,y_pred)}')
    print(f'Fbeta-score: {fbeta_score(y_test,y_pred,beta=0.5)}')
    print(classification_report(y_test,y_pred))
    print('-'*33)
    

using LR: 
Training Accuracy :0.7587575899112564
Testing Accuracy :0.691544885177453
Confusion matrix:
 [[1207  415]
 [ 176  118]]
Recall: 0.4013605442176871
precision: 0.22138836772983114
F1-score: 0.28536880290205563
Fbeta-score: 0.24319868095630665
              precision    recall  f1-score   support

           0       0.87      0.74      0.80      1622
           1       0.22      0.40      0.29       294

    accuracy                           0.69      1916
   macro avg       0.55      0.57      0.54      1916
weighted avg       0.77      0.69      0.72      1916

---------------------------------
using KNN: 
Training Accuracy :0.8552856920442161
Testing Accuracy :0.6644050104384134
Confusion matrix:
 [[1173  449]
 [ 194  100]]
Recall: 0.3401360544217687
precision: 0.18214936247723132
F1-score: 0.23724792408066428
Fbeta-score: 0.20080321285140562
              precision    recall  f1-score   support

           0       0.86      0.72      0.78      1622
           1       0.18 

C:\Users\mgama\conda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:51:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy :0.959598318542737
Testing Accuracy :0.7687891440501043
Confusion matrix:
 [[1412  210]
 [ 233   61]]
Recall: 0.20748299319727892
precision: 0.22509225092250923
F1-score: 0.215929203539823
Fbeta-score: 0.22133526850507984
              precision    recall  f1-score   support

           0       0.86      0.87      0.86      1622
           1       0.23      0.21      0.22       294

    accuracy                           0.77      1916
   macro avg       0.54      0.54      0.54      1916
weighted avg       0.76      0.77      0.76      1916

---------------------------------
using RF: 
Training Accuracy :1.0
Testing Accuracy :0.7776617954070981
Confusion matrix:


In [58]:
df=pd.read_csv('datasets/sentiment.csv',sep='\t',names=['liked','tweet'])
df

liked                                              tweet
0         1            The Da Vinci Code book is just awesome.
1         1  this was the first clive cussler i've ever rea...
2         1                   i liked the Da Vinci Code a lot.
3         1                   i liked the Da Vinci Code a lot.
4         1  I liked the Da Vinci Code but it ultimatly did...
...     ...                                                ...
6913      0                     Brokeback Mountain was boring.
6914      0       So Brokeback Mountain was really depressing.
6915      0  As I sit here, watching the MTV Movie Awards, ...
6916      0    Ok brokeback mountain is such a horrible movie.
6917      0   Oh, and Brokeback Mountain was a terrible movie.

[6918 rows x 2 columns]

In [59]:
x=df['tweet']
y=df['liked']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words='english')
x_train=vectorizer.fit_transform(x_train)
x_test=vectorizer.transform(x_test)
x_train

<5534x1661 sparse matrix of type '<class 'numpy.float64'>'
	with 34177 stored elements in Compressed Sparse Row format>

In [61]:
tf_df=pd.DataFrame(x_train.toarray(),columns=vectorizer.get_feature_names())
tf_df

00  007   10   16   17  1st  200  2007  2nd   30  ...   ya  yahoo  \
0     0.443173  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
1     0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
2     0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
3     0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
4     0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
...        ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...  ...    ...   
5529  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
5530  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
5531  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
5532  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   
5533  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0    0.0   

      yea  yeah  year  yes  yesterday  young  zach  zen  
0     0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
1     0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
2     0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
3     0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
4     0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
...   ...   ...   ...  ...        ...    ...   ...  ...  
5529  0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
5530  0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
5531  0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
5532  0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  
5533  0.0   0.0   0.0  0.0        0.0    0.0   0.0  0.0  

[5534 rows x 1661 columns]

In [63]:
from sklearn.naive_bayes import MultinomialNB
models={
    'LR':LogisticRegression(),
    'KNN':KNeighborsClassifier(),
    'DT':DecisionTreeClassifier(),
    'SVC':SVC(),
    'NB':MultinomialNB(),
    'XGC':XGBClassifier(),
    'RF':RandomForestClassifier()
    
}

In [64]:


for name,model in  models.items():
    print(f'using {name}: ')
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f'Training Accuracy :{accuracy_score(y_train,model.predict(x_train))}')
    print(f'Testing Accuracy :{accuracy_score(y_test,y_pred)}')
    print(f'Confusion matrix:\n {confusion_matrix(y_test,y_pred)}')
    print(f'Recall: {recall_score(y_test,y_pred)}')
    print(f'precision: {precision_score(y_test,y_pred)}')
    print(f'F1-score: {f1_score(y_test,y_pred)}')
    print(f'Fbeta-score: {fbeta_score(y_test,y_pred,beta=0.5)}')
    print(classification_report(y_test,y_pred))
    print('-'*33)
    

using LR: 
Training Accuracy :0.9976508854354897
Testing Accuracy :0.9913294797687862
Confusion matrix:
 [[594  10]
 [  2 778]]
Recall: 0.9974358974358974
precision: 0.9873096446700508
F1-score: 0.9923469387755102
Fbeta-score: 0.9893184130213634
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       604
           1       0.99      1.00      0.99       780

    accuracy                           0.99      1384
   macro avg       0.99      0.99      0.99      1384
weighted avg       0.99      0.99      0.99      1384

---------------------------------
using KNN: 
Training Accuracy :0.9859053126129382
Testing Accuracy :0.9783236994219653
Confusion matrix:
 [[578  26]
 [  4 776]]
Recall: 0.9948717948717949
precision: 0.9675810473815462
F1-score: 0.9810366624525916
Fbeta-score: 0.9729187562688064
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       604
           1       0.97      0.99    

C:\Users\mgama\conda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[16:04:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy :0.9996385977593061
Testing Accuracy :0.9884393063583815
Confusion matrix:
 [[592  12]
 [  4 776]]
Recall: 0.9948717948717949
precision: 0.9847715736040609
F1-score: 0.9897959183673469
Fbeta-score: 0.9867751780264497
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       604
           1       0.98      0.99      0.99       780

    accuracy                           0.99      1384
   macro avg       0.99      0.99      0.99      1384
weighted avg       0.99      0.99      0.99      1384

---------------------------------
using RF: 
Training Accuracy :1.0
Testing Accuracy :0.9877167630057804
Confusion matrix:
 [[58

In [65]:
model=LogisticRegression()
model.fit(x_train,y_train)


LogisticRegression()

In [66]:
import joblib
joblib.dump(model,'model_sent.h5')
joblib.dump(vectorizer,'vectorizer.h5')


['vectorizer.h5']

In [70]:
x_=vectorizer.transform(['I don\'t want to watch a Movie'])
y_pred_=model.predict(x_)
y_pred_

array([1], dtype=int64)